# Generated by Django 4.2.14 on 2024-08-06 12:00

import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtailcore", "0089_log_entry_data_json_null_to_object"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReadOnlyGroupTask",
            fields=[
                (
                    "task_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.task",
                    ),
                ),
                ("groups", models.ManyToManyField(to="auth.group")),
            ],
            options={
                "verbose_name": "Read-only Group approval task",
                "verbose_name_plural": "Read-only Group approval tasks",
            },
            bases=("wagtailcore.task",),
        ),
    ]
